spring:
  application:
    name: system
  datasource:
    #    url: jdbc:mysql://182.92.155.84:3306/kele?characterEncoding=utf8&serverTimezone=GMT%2B8
    url: jdbc:mysql://127.0.0.1:3306/dcz?characterEncoding=utf8&serverTimezone=GMT%2B8
    username: root
    password: root
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    database: MYSQL
    show-sql: false
    hibernate:
      ddl-auto: none
  jackson:
    time-zone: GMT+8
    default-property-inclusion: non_null
server:
  port: 8082
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
