# 设置spring应用命名，可以自定义，非必要
spring:
  application:
    name: eureka-server
server:
  port: 8761  # 设置Eureka Server WEB控制台端口，自定义
eureka:
  client:
    registerWithEureka: false #是否将自己注册到Eureka-Server中，默认的为true
    fetchRegistry: false  #是否从Eureka-Server中获取服务注册信息，默认为true
